version: "3.2"
services:
   
    node_1:
        container_name: node_1
        image: cockroachdb/cockroach:v21.1.11
        volumes:
           - ./data1/node1:/cockroach/cockroach-data
        command: start --insecure  --join node_1,node_2 
        ports:
           - "26257:26257"
           - "8080:8080"
        networks:
            cockroachdb_net:
                aliases:
                   - node_1

    node_2:
        container_name: node_2
        image: cockroachdb/cockroach:v21.1.11
        volumes:
           - ./data1/node2:/cockroach/cockroach-data
        command: start --insecure  --join=node_1,node_2 
        networks:
            cockroachdb_net:
                aliases:
                   - node_2


networks:
    cockroachdb_net:
        driver: bridge